//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CummulativeRespons
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int AnswerId { get; set; }
        public int CummulativeId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual CumulativeTestsPassed CumulativeTestsPassed { get; set; }
        public virtual Question Question { get; set; }
    }
}
