//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualQuizPassed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndividualQuizPassed()
        {
            this.IndividualResponses = new HashSet<IndividualRespons>();
        }
    
        public int Id { get; set; }
        public int DisciplineId { get; set; }
        public int LectureId { get; set; }
        public int StudentId { get; set; }
        public bool IsPassed { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Lecture Lecture { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualRespons> IndividualResponses { get; set; }
    }
}
