//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleHistory
    {
        public int Id { get; set; }
        public int LectureHistoryId { get; set; }
        public int ModuleId { get; set; }
    }
}
