//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingModule.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testingDbEntities : DbContext
    {
        public testingDbEntities()
            : base("name=testingDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Lecture> Lectures { get; set; }
        public virtual DbSet<LecturesHistory> LecturesHistories { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Respons> Responses { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Lector> Lectors { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<LectorDiscipline> LectorDisciplines { get; set; }
        public virtual DbSet<StudentDiscipline> StudentDisciplines { get; set; }
    }
}
